---
version: '3.8'
networks:
  traefik:
    external: true
    name: traefik
services:
  traefik:
    image: traefik:v2.4.5
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: host
    - target: 443
      published: 443
      protocol: tcp
      mode: host
    networks:
      traefik: {}
    labels:
      traefik.enable: 'false'
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "${PWD}/conf/traefik/traefik-prod.yaml:/etc/traefik/traefik.yaml"
    - "${PWD}/conf/traefik/traefik-dev.yaml:/etc/traefik/traefik.yaml"
