---
services:
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    restart: always
    volumes:
      - wordpress:/var/www/html
    env_file:
      - ${PWD}/.env
    networks:
      traefik: {}
      wordpress: {}
    labels:
      traefik.enable: "true"
      traefik.http.routers.wordpress.rule:
        PathPrefix(`/`)
      traefik.http.routers.wordpress.entrypoints: http,https
      traefik.http.routers.wordpress.service: wordpress
      traefik.http.routers.wordpress.middlewares: compress@docker
      traefik.http.services.wordpress.loadbalancer.server.port: 80
      traefik.http.services.wordpress.loadbalancer.server.scheme: http
      traefik.http.middlewares.compress.compress: "true"
