---
services:
  traefik:
    image: traefik:v2.4.5

    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host

      - target: 443
        published: 443
        protocol: tcp
        mode: host

    networks:
      traefik: {}

    labels:
      traefik.enable: "false"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
